### ISSUE TITLE
Popup to display data security plan

### ISSUE THREAD

**Issue by ajlouie** [ithriv/ithriv_web#100]
Every time a commons HSD dataset download is clicked, a simple popup should appear requesting user to confirm that they have read the data security plan for the project/dataset and are accepting all the risks associated prior to allowing them to download.

**Comment by rkc7h** [comment]
The Pop text should display the following 
"I confirm that I have reviewed the Data Security Plan.  I am saving this file to a location listed on my DSP and approved for Highly Sensitive Data."
