### ISSUE TITLE
Build adhoc popup and notification service.

### ISSUE THREAD

**Issue by rkc7h** [ithriv/ithriv_web#110]
Build custom notification service to display custom popups and track user accepting the policies before allowing a user to  access commons objects. Ravi to provide more specifics on design.

**Comment by ajlouie** [comment]
- [ ] Backend (`ithriv_service`):
    - [ ] Add UserNotifications table
        - [ ] `id`: int
        - [ ] `title_sent`: string of NotificationActions title sent to user
        - [ ] `description_sent`: string of NotificationActions description sent to user
        - [ ] `actions_sent`: list of NotificationActions sent to user
        - [ ] `date_created`: datetime
        - [ ] `last_updated`: datetime
        - [ ] `expiration_date`: datetime
        - [ ] `action_ids`: list of possible NotificationActions the user can take. foreign key to Actions table
        - [ ] `user_id`: foreign key to Users table
        - [ ] `status`: enum (unread | read | action_taken)
        - [ ] `action_taken_id`: foreign key of action taken
        - [ ] `action_taken_date`: datetime of when action was taken
    - [ ] Add NotificationActions table
        - [ ] `id`: int
        - [ ] `type`: enum?
        - [ ] `date_created`: datetime for versioning
        - [ ] `last_updated`: datetime for versioning
        - [ ] `current_version`: foreign key from NotificationActionVersions table
    - [ ] Add NotificationActionVersions table
        - [ ] `id`: int
        - [ ] `title`: string
        - [ ] `description`: string
        - [ ] `date_created`: datetime for versioning
        - [ ] `last_updated`: datetime for versioning
        - [ ] `notification_action_id`: foreign key to NotificationActions table
    - [ ] Add Notifications endpoints
        - [ ] get
            - [ ] params: user_id, status
            - [ ] response: list of UserNotifications for the given user_id
        - [ ] update
            - [ ] params: user_notification_id, action_taken_id, status
- [ ] Frontend (`ithriv_web`)
    - [ ] Notifications inbox
        - [ ] Mark as read
        - [ ] Mark as unread?
        - [ ] Display notifications --> calls get endpoint
        - [ ] Take action on notification --> calls update endpoint
        - [ ] Sort/filter by status or date

**Comment by rkc7h** [comment]
Requirement: 

The first time a user enters the Research Data Commons, they should be presented with an End User Agreement (pop-up).  Once they select "Agree", the pop-up disappears and they login to project list view.  They do not see the message again, until an admin decides to push new updated agreement.  After that push, all users will again have to AGREE once to new version of the text.

Version 1 text:
I agree to abide by all instutional policies regarding data classification, storage, sharing, and publication.  This includes, but is not limited to, appropriate use of HIPAA governed data.

I will not use this system for storage of CUI data.  

 FUTURE: ALLOW UPDATES: Admin decides to push new updated agreement.  After that push, all users will again have to AGREE once to new version of the text.
 
Ravi: We are not aiming to implement future requirement at this stage and the intention at this stage is to reutilize the existing dialog created for IRB integration by displaying a dialog  with text above and capture the response.. ravi@slack for further questions on this
