### ISSUE TITLE
Missing resources in search

### ISSUE THREAD

**Issue by JohannaLoomba** [ithriv/ithriv_web#18]
BUG: Some resource pages are not showing up in the search, even for users who have access to those pages.  This includes "Patient Cohort Analysis Tool: TriNetX Live" - this is one of our most important UVA resources.  Ravi: see email I forwarded on 6/3 from Fauzia.

**Comment by JohannaLoomba** [comment]
@rkc7h Hi Ravi - the resources that were previously missing in search results are there now.  Did you do something to fix it, or is this just erratic behavior?

**Comment by rkc7h** [comment]
@JohannaLoomba It is possible as it might got fixed as part of changes I made to search during last release. I would wait on this this issue until the fix persists the next release as well.

**Comment by rkc7h** [comment]
@JohannaLoomba since we had another release yesterday, can you please verify if the fix still persisted so that we can close this one.

**Comment by JohannaLoomba** [comment]
Looks fixed to me!
