### ISSUE TITLE
broken links to sections and categories in HELP/SITE MAP

### ISSUE THREAD

**Issue by JohannaLoomba** [ithriv/ithriv_web#36]
When you go to Help - > Site Map, the links in listed for the site map are broken.  In the past the links would take us to the respective category.  The links look like this: https://portal.ithriv.org/category/1.  However, they should have a # in the URL: https://portal.ithriv.org/#/category/1.  The links to the sections are also not working.

**Comment by rkc7h** [comment]
Hi @JohannaLoomba. I fixed this changes and also added a way to scroll on subcategories aswell in addition to fixing the link. Please move this issues project board to accepted from UAT on the project link https://github.com/orgs/ithriv/projects/5

**Comment by rkc7h** [comment]
hi @JohannaLoomba as we spoke yesterday. I was able handle the sitemap based on device as well as the view a person prefers to browse resources. Can you please verify as well and move the issue status to "Accepted" on the following project link ASAP @ https://github.com/orgs/ithriv/projects/5. I shall schedule the milestone release today.

**Comment by rkc7h** [comment]
@JohannaLoomba can you please close this request when you get a chance
