### ISSUE TITLE
icons on resources/events should link to a filtered search

### ISSUE THREAD

**Issue by JohannaLoomba** [ithriv/ithriv_web#39]
Clicking the type icon or the institution icon on small tiles should take you to the search page and filter results based on that selection.  For example, if you click the funding type icon on a resource tile, you should be directed to the search page with Type = Funding Source filter applied.

For some reason this functionality that worked in the past is now broken.  Note that this functionality is exactly the same as what happens when you are on a resource/event page.  From within a page, there is an information pane to the right.  Both TYPE and INSTITUTION are hyperlinks.  When you click those hyperlinks, you are taken to the search page with filter applied.  The icons on the smaller tiles should work exactly like these hyperlinks.

**Comment by rkc7h** [comment]
@JohannaLoomba when you get sometime can you please review this issue in Prod and close this issue ?
