### ISSUE TITLE
Missing search field: Public vew

### ISSUE THREAD

**Issue by JohannaLoomba** [ithriv/ithriv_web#45]
I just noticed that the search field is missing when you login as public.  Was this an intentional change?  The public users should be able to search, but of course results will be limited to anything that is NOT PRIVATE. @rkc7h

**Comment by rkc7h** [comment]
Hi @JohannaLoomba it was an intentional change if you remember as we now moved search to make it only visible when after you click one amount "Learn", "Propose", "Connect" and "Conduct"

**Comment by JohannaLoomba** [comment]
@rkc7h I am sorry Ravi, but I do not remember any such requirement.  To me there is no reason to hide search while on the main public view.  I do know we need to hide consult button from public (all views) which appears to still be working fine.  I apologize for any misunderstanding about hiding search button.

**Comment by JohannaLoomba** [comment]
Fixed
