### ISSUE TITLE
New Resources/Events - description not showing

### ISSUE THREAD

**Issue by JohannaLoomba** [ithriv/ithriv_web#69]
Hello Ravi,
For recently created pages, the first part of the description is not showing on the small tiles. It either shows up blank or looks like <p...
Go to https://portal.ithriv.org/#/category/1039 and see how tiles look there.
Maybe issue with new Angular version?

**Comment by JohannaLoomba** [comment]
Hi Ravi - Should I close this issue or should I wait for for you to indicate it has been moved to live site?

**Comment by rkc7h** [comment]
Hi Johanna,

I indicated it has been moved to production. You may verify to your satisfaction and close it.

Regards,
Ravi
