### ISSUE TITLE
IRB Security plan lookup for highly sensitive data

### ISSUE THREAD

**Issue by rkc7h** [ithriv/ithriv_web#92]
Refine permissions for highly sensitive data (use IRB rest API to limit who can be assigned permissions)

1. If HSD flag is set and user has add/edit permissions, user is only selecting from dropdown of people listed on the IRB.  "Select only the individuals working under HIPAA-covered entity per IRB documentation" (Respective landing service to provide api to fetch the emails listed on IRB and also checks and provides the HSD access allowed flag against the IRB security plan). 
2. User only views the datasets he/she has permissions to. (backend function).

**Comment by ajlouie** [comment]
Frontend feature branch is in development here:
https://github.com/ajlouie/ithriv_web-1/tree/feature/irb_permissions

**Comment by rkc7h** [comment]
Notes from Johanna

1.       User is adding a new dataset and the IRB protocol field needs to list all IRB protocols that user is associated with (you send IRB user id, they send you list of protocol numbers). FEATURE # 8079

 
2.       User is adding permissions to a HSD dataset.  The user is presented with a list of people they can select from (you send IRB a protocol number and they send you list of people in roles 1-6 as these are people the user can select from).  FEATURE #8285

 
3.       User clicks on Project and sees lists of datasets they can access.  Before rending the list, we check that they are STILL active on IRB protocol for any HSD datasets they have been assigned a role on (you send IRB a userID and dataset and they tell you if person active on it).  FEATURE #11399

**Comment by rkc7h** [comment]
@ajlouie as we spoke following are API specs to expect from Commons backend. Let me know if you would need anything else or have any questions.  

1. /commons/permissions/user/irb_protocols - Gets the list of IRB studies that the given user has access to. If the user doesn’t have access to any studies, returns an empty list.
Response:
[
  {
    "study_id": "ABC123456789",
  },
  {
    "study_id": "sfd123456789",
  },
  ...
]
2. /commons/permissions/datasets/investigator/<dataset_id>
Parameters:
identifier (int) - ID of the dataset
Response:
[
  {
    "email": "ajl2j@virginia.edu",
  },
  {
    "email": "pkd2e@virginia.edu",
  },
  {
    "email": "rkc7h@virginia.edu",
  },
  ...
]
3. Dataset Meatadaa will now include a flag isLocked (Mandatory).
